<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Svetlanas-MacBook-Pro.local" name="Calculator - all-tests" tests="58" failures="12" timestamp="23 Jun 2017 23:12:43 GMT" time="0.053" errors="0">
  <testcase name="testDivByOne" time="0.0" classname="javatest.com.epam.cdp.testngtests.DoubleDivTest"/>
  <testcase name="testDivByZero" time="0.0" classname="javatest.com.epam.cdp.testngtests.DoubleDivTest"/>
  <testcase name="cos0" time="0.0" classname="javatest.com.epam.cdp.testngtests.TrigonometryTest">
    <failure type="java.lang.AssertionError" message="expected [1.0] but found [0.0]">
      <![CDATA[java.lang.AssertionError: expected [1.0] but found [0.0]
	at javatest.com.epam.cdp.testngtests.TrigonometryTest.cos0(TrigonometryTest.java:33)
	at javatest.com.epam.cdp.testngtests.TestRunner.main(TestRunner.java:28)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- cos0 -->
  <testcase name="cos60" time="0.0" classname="javatest.com.epam.cdp.testngtests.TrigonometryTest">
    <failure type="java.lang.AssertionError" message="expected [0.5] but found [0.0]">
      <![CDATA[java.lang.AssertionError: expected [0.5] but found [0.0]
	at javatest.com.epam.cdp.testngtests.TrigonometryTest.cos60(TrigonometryTest.java:39)
	at javatest.com.epam.cdp.testngtests.TestRunner.main(TestRunner.java:28)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- cos60 -->
  <testcase name="ctg0" time="0.0" classname="javatest.com.epam.cdp.testngtests.TrigonometryTest">
    <failure type="org.testng.TestException" message="
Expected exception java.lang.NumberFormatException but got org.testng.TestException: 
Method TrigonometryTest.ctg0()[pri:0, instance:javatest.com.epam.cdp.testngtests.TrigonometryTest@27082746] should have thrown an exception of class java.lang.NumberFormatException">
      <![CDATA[org.testng.TestException: 
Method TrigonometryTest.ctg0()[pri:0, instance:javatest.com.epam.cdp.testngtests.TrigonometryTest@27082746] should have thrown an exception of class java.lang.NumberFormatException
	at javatest.com.epam.cdp.testngtests.TestRunner.main(TestRunner.java:28)
Method TrigonometryTest.ctg0()[pri:0, instance:javatest.com.epam.cdp.testngtests.TrigonometryTest@27082746] should have thrown an exception of class java.lang.NumberFormatException
	... 15 more
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- ctg0 -->
  <testcase name="ctg45" time="0.0" classname="javatest.com.epam.cdp.testngtests.TrigonometryTest"/>
  <testcase name="sin0" time="0.0" classname="javatest.com.epam.cdp.testngtests.TrigonometryTest"/>
  <testcase name="sin30" time="0.0" classname="javatest.com.epam.cdp.testngtests.TrigonometryTest">
    <failure type="java.lang.AssertionError" message="expected [0.5] but found [-0.9880316240928618]">
      <![CDATA[java.lang.AssertionError: expected [0.5] but found [-0.9880316240928618]
	at javatest.com.epam.cdp.testngtests.TrigonometryTest.sin30(TrigonometryTest.java:20)
	at javatest.com.epam.cdp.testngtests.TestRunner.main(TestRunner.java:28)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- sin30 -->
  <testcase name="sin90" time="0.0" classname="javatest.com.epam.cdp.testngtests.TrigonometryTest">
    <failure type="java.lang.AssertionError" message="expected [1.0] but found [0.8939966636005579]">
      <![CDATA[java.lang.AssertionError: expected [1.0] but found [0.8939966636005579]
	at javatest.com.epam.cdp.testngtests.TrigonometryTest.sin90(TrigonometryTest.java:27)
	at javatest.com.epam.cdp.testngtests.TestRunner.main(TestRunner.java:28)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- sin90 -->
  <testcase name="tg0" time="0.0" classname="javatest.com.epam.cdp.testngtests.TrigonometryTest">
    <failure type="java.lang.AssertionError" message="expected [0.0] but found [NaN]">
      <![CDATA[java.lang.AssertionError: expected [0.0] but found [NaN]
	at javatest.com.epam.cdp.testngtests.TrigonometryTest.tg0(TrigonometryTest.java:45)
	at javatest.com.epam.cdp.testngtests.TestRunner.main(TestRunner.java:28)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- tg0 -->
  <testcase name="tg45" time="0.0" classname="javatest.com.epam.cdp.testngtests.TrigonometryTest"/>
  <testcase name="tg90" time="0.0" classname="javatest.com.epam.cdp.testngtests.TrigonometryTest">
    <failure type="org.testng.TestException" message="
Expected exception java.lang.NumberFormatException but got org.testng.TestException: 
Method TrigonometryTest.tg90()[pri:0, instance:javatest.com.epam.cdp.testngtests.TrigonometryTest@27082746] should have thrown an exception of class java.lang.NumberFormatException">
      <![CDATA[org.testng.TestException: 
Method TrigonometryTest.tg90()[pri:0, instance:javatest.com.epam.cdp.testngtests.TrigonometryTest@27082746] should have thrown an exception of class java.lang.NumberFormatException
	at javatest.com.epam.cdp.testngtests.TestRunner.main(TestRunner.java:28)
Method TrigonometryTest.tg90()[pri:0, instance:javatest.com.epam.cdp.testngtests.TrigonometryTest@27082746] should have thrown an exception of class java.lang.NumberFormatException
	... 15 more
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- tg90 -->
  <testcase name="testSum" time="0.0" classname="javatest.com.epam.cdp.testngtests.DoubleSumTest"/>
  <testcase name="testSum" time="0.001" classname="javatest.com.epam.cdp.testngtests.DoubleSumTest"/>
  <testcase name="testSum" time="0.001" classname="javatest.com.epam.cdp.testngtests.DoubleSumTest"/>
  <testcase name="testSum" time="0.0" classname="javatest.com.epam.cdp.testngtests.DoubleSumTest"/>
  <testcase name="testSum" time="0.0" classname="javatest.com.epam.cdp.testngtests.DoubleSumTest"/>
  <testcase name="testDivByInt" time="0.0" classname="javatest.com.epam.cdp.testngtests.LongDivTest">
    <failure type="java.lang.AssertionError" message="expected [75] but found [75.0]">
      <![CDATA[java.lang.AssertionError: expected [75] but found [75.0]
	at javatest.com.epam.cdp.testngtests.LongDivTest.testDivByInt(LongDivTest.java:24)
	at javatest.com.epam.cdp.testngtests.TestRunner.main(TestRunner.java:28)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- testDivByInt -->
  <testcase name="testDivByLong" time="0.0" classname="javatest.com.epam.cdp.testngtests.LongDivTest">
    <failure type="java.lang.AssertionError" message="expected [1.33] but found [1.0]">
      <![CDATA[java.lang.AssertionError: expected [1.33] but found [1.0]
	at javatest.com.epam.cdp.testngtests.LongDivTest.testDivByLong(LongDivTest.java:30)
	at javatest.com.epam.cdp.testngtests.TestRunner.main(TestRunner.java:28)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- testDivByLong -->
  <testcase name="testDivByNeg" time="0.0" classname="javatest.com.epam.cdp.testngtests.LongDivTest"/>
  <testcase name="testDivByOne" time="0.001" classname="javatest.com.epam.cdp.testngtests.LongDivTest">
    <failure type="java.lang.AssertionError" message="expected [340] but found [340.0]">
      <![CDATA[java.lang.AssertionError: expected [340] but found [340.0]
	at javatest.com.epam.cdp.testngtests.LongDivTest.testDivByOne(LongDivTest.java:18)
	at javatest.com.epam.cdp.testngtests.TestRunner.main(TestRunner.java:28)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- testDivByOne -->
  <testcase name="testDivByZero" time="0.0" classname="javatest.com.epam.cdp.testngtests.LongDivTest"/>
  <testcase name="testSum" time="0.0" classname="javatest.com.epam.cdp.testngtests.LongSumTest"/>
  <testcase name="testSum" time="0.001" classname="javatest.com.epam.cdp.testngtests.LongSumTest"/>
  <testcase name="testSum" time="0.0" classname="javatest.com.epam.cdp.testngtests.LongSumTest"/>
  <testcase name="testSum" time="0.0" classname="javatest.com.epam.cdp.testngtests.LongSumTest"/>
  <testcase name="testSum" time="0.001" classname="javatest.com.epam.cdp.testngtests.LongSumTest"/>
  <testcase name="DoubleMultTest" time="0.0" classname="javatest.com.epam.cdp.testngtests.MultTest"/>
  <testcase name="DoubleMultTest" time="0.0" classname="javatest.com.epam.cdp.testngtests.MultTest">
    <failure type="java.lang.AssertionError" message="expected [-0.34] but found [-1.0]">
      <![CDATA[java.lang.AssertionError: expected [-0.34] but found [-1.0]
	at javatest.com.epam.cdp.testngtests.MultTest.DoubleMultTest(MultTest.java:41)
	at javatest.com.epam.cdp.testngtests.TestRunner.main(TestRunner.java:28)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- DoubleMultTest -->
  <testcase name="DoubleMultTest" time="0.0" classname="javatest.com.epam.cdp.testngtests.MultTest"/>
  <testcase name="DoubleMultTest" time="0.0" classname="javatest.com.epam.cdp.testngtests.MultTest"/>
  <testcase name="LongMultTest" time="0.0" classname="javatest.com.epam.cdp.testngtests.MultTest"/>
  <testcase name="LongMultTest" time="0.001" classname="javatest.com.epam.cdp.testngtests.MultTest"/>
  <testcase name="LongMultTest" time="0.0" classname="javatest.com.epam.cdp.testngtests.MultTest"/>
  <testcase name="LongMultTest" time="0.001" classname="javatest.com.epam.cdp.testngtests.MultTest"/>
  <testcase name="LongMultTest" time="0.0" classname="javatest.com.epam.cdp.testngtests.MultTest"/>
  <testcase name="testPowByDouble" time="0.0" classname="javatest.com.epam.cdp.testngtests.PowSqrtTest"/>
  <testcase name="testPowByInt" time="0.0" classname="javatest.com.epam.cdp.testngtests.PowSqrtTest"/>
  <testcase name="testPowByNeg" time="0.0" classname="javatest.com.epam.cdp.testngtests.PowSqrtTest"/>
  <testcase name="testPowByOne" time="0.0" classname="javatest.com.epam.cdp.testngtests.PowSqrtTest"/>
  <testcase name="testPowByZero" time="0.0" classname="javatest.com.epam.cdp.testngtests.PowSqrtTest"/>
  <testcase name="testSqrtOfDouble" time="0.0" classname="javatest.com.epam.cdp.testngtests.PowSqrtTest"/>
  <testcase name="testSqrtOfInt" time="0.0" classname="javatest.com.epam.cdp.testngtests.PowSqrtTest"/>
  <testcase name="testSqrtOfNeg" time="0.001" classname="javatest.com.epam.cdp.testngtests.PowSqrtTest">
    <failure type="java.lang.AssertionError" message="expected [-1.732] but found [1.732]">
      <![CDATA[java.lang.AssertionError: expected [-1.732] but found [1.732]
	at javatest.com.epam.cdp.testngtests.PowSqrtTest.testSqrtOfNeg(PowSqrtTest.java:69)
	at javatest.com.epam.cdp.testngtests.TestRunner.main(TestRunner.java:28)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- testSqrtOfNeg -->
  <testcase name="testSqrtOfOne" time="0.0" classname="javatest.com.epam.cdp.testngtests.PowSqrtTest"/>
  <testcase name="testSqrtOfZero" time="0.0" classname="javatest.com.epam.cdp.testngtests.PowSqrtTest"/>
  <testcase name="doubleSub" time="0.0" classname="javatest.com.epam.cdp.testngtests.SubTest"/>
  <testcase name="doubleSub" time="0.0" classname="javatest.com.epam.cdp.testngtests.SubTest"/>
  <testcase name="doubleSub" time="0.0" classname="javatest.com.epam.cdp.testngtests.SubTest"/>
  <testcase name="doubleSub" time="0.0" classname="javatest.com.epam.cdp.testngtests.SubTest"/>
  <testcase name="doubleSub" time="0.0" classname="javatest.com.epam.cdp.testngtests.SubTest"/>
  <testcase name="longSub" time="0.0" classname="javatest.com.epam.cdp.testngtests.SubTest"/>
  <testcase name="longSub" time="0.0" classname="javatest.com.epam.cdp.testngtests.SubTest"/>
  <testcase name="longSub" time="0.0" classname="javatest.com.epam.cdp.testngtests.SubTest"/>
  <testcase name="longSub" time="0.0" classname="javatest.com.epam.cdp.testngtests.SubTest"/>
  <testcase name="longSub" time="0.0" classname="javatest.com.epam.cdp.testngtests.SubTest"/>
  <testcase name="longSub" time="0.0" classname="javatest.com.epam.cdp.testngtests.SubTest"/>
  <testcase name="longSub" time="0.0" classname="javatest.com.epam.cdp.testngtests.SubTest"/>
</testsuite> <!-- Calculator - all-tests -->
